name: release

on:
  workflow_dispatch:
    inputs:
      version: 
        type: string
        required: true
        description: the version
      sha256_mac_x86_64:
        type: string
        required: true
        description: sha256 for x86_64 binary

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Edit ruby file
        # https://bit.ly/3QoTtN0
        run: |
          sed -i -E -z "s@[0-9]\.[0-9]\.[0-9]@${{ inputs.version }}@g" ./ro-soku.rb
          sed -i -E -z "s@ro-soku_x86_64_mac\"\\n[[:space:]]+sha256 \"[a-f0-9]{64}@ro-soku_x86_64_mac\"\\n  sha256 \"${{ inputs.sha256_mac_x86_64 }}@g" ./ro-soku.rb

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PAT }}
